# Generated by Django 3.0.2 on 2020-08-24 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_bannerimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerimg',
            old_name='image',
            new_name='bannerimage',
        ),
    ]
