# Generated by Django 3.0.2 on 2020-08-24 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200824_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimg',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
