# Generated by Django 3.0.2 on 2020-08-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_bannerimg_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
