# Generated by Django 3.0.2 on 2020-08-24 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_contactmodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='callout',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
