# Generated by Django 3.0.2 on 2020-08-24 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_item_callout'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='extra_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
