# Generated by Django 3.0.2 on 2020-08-24 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_item_extra_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='intro_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Sports'), ('H', 'Health & Beauty'), ('B', 'Books'), ('MF', 'Men Fashion'), ('SW', 'Software'), ('K', 'Kids & Babies'), ('E', 'Electronics')], max_length=2),
        ),
    ]
